name: Publish Docker image
on:
  release:
    types: [published, edited]
jobs:
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
          echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
      - name: Run docker build
        run: make docker-build
      - name: Tag docker image
        run: docker tag cerc-io/ipld-eth-db git.vdb.to/cerc-io/ipld-eth-db/ipld-eth-db:${{steps.vars.outputs.sha}}
      - name: Tag docker image
        run: docker tag git.vdb.to/cerc-io/ipld-eth-db/ipld-eth-db:${{steps.vars.outputs.sha}} git.vdb.to/cerc-io/ipld-eth-db:${{steps.vars.outputs.tag}}
      - name: Docker Login
        run: echo ${{ secrets.GITEA_TOKEN }} | docker login https://git.vdb.to -u cerccicd --password-stdin
      - name: Docker Push
        run: docker push git.vdb.to/cerc-io/ipld-eth-db/ipld-eth-db:${{steps.vars.outputs.sha}}
      - name: Docker Push with TAG to git.vdb.to
        run: docker push git.vdb.to/cerc-io/ipld-eth-db/ipld-eth-db:${{steps.vars.outputs.tag}}
  #push_to_registries:
  #  name: Push Docker image to Docker Hub
  #  runs-on: ubuntu-latest
  #  needs: build
  #  steps:
  #    - name: Get the version
  #     id: vars
  #      run: |
  #        echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
  #        echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
  #    - name: Docker Login to Github Registry
  #      run: echo ${{ secrets.GITEA_TOKEN }} | docker login https://git.vdb.to -u cerccicd --password-stdin
  #    - name: Docker Pull
  #      run: docker pull git.vdb.to/cerc-io/ipld-eth-db/ipld-eth-db:${{steps.vars.outputs.sha}}
  #    - name: Docker Push to Docker Hub
      #      run: docker push cerc-io/ipld-eth-db:${{steps.vars.outputs.tag}}
  #    - name: Docker Login to Docker Registry
  #      run: echo ${{ secrets.VULCANIZEJENKINS_PAT }} | docker login -u cerccicd --password-stdin
  #    - name: Tag docker image
  #      run: docker tag git.vdb.to/cerc-io/ipld-eth-db/ipld-eth-db:${{steps.vars.outputs.sha}} cerc-io/ipld-eth-db:${{steps.vars.outputs.tag}}
  #    - name: Docker Push to Docker Hub
  #      run: docker push cerc-io/ipld-eth-db:${{steps.vars.outputs.tag}}
